# 开发步骤  导入配置, 编写依赖
server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
    # 连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/codingce/springcloud-config.git  # 是https的, 不是git

# 通过config-server 可以连接到git 访问其中的资源以及配置  http://localhost:3344/application-dev.yml   http://localhost:3344/application/dev/master
# config-server服务端        gitee地址：https://gitee.com/codingce/springcloud-config.git